apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 30010
    protocol: TCP
  selector:
    service: zookeeper
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
      restartPolicy: Always