apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-cluster
  name: kafka-cluster
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30002
  selector:
    service: kafka-cluster
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-cluster
  template:
    metadata:
      labels:
        service: kafka-cluster
    spec:
      hostname: kafka-cluster
      containers:
      - image: wurstmeister/kafka
        name: kafka-cluster
        imagePullPolicy: Always
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
